### ISSUE TITLE
Adding transmissions to base game tractors

### ISSUE THREAD

**Issue by rubberburner89** [modelleicher/FS19_realManualTransmission#16]
I'm trying to add some transmissions to some of the base game tractors. I know the mod is still beta so I figured I'd take it upon myself (for personal use only of course). But when I add them to the basegameConfigs.xml it throws an error stating that the .xml is not a mod.

**Comment by modelleicher** [comment]
Hi,
Thats not an Error thats a Debug Print I left in there to debug.. it just points out that it found an XML in the basegameConfigs that isn't a mod. I guess its reverse from what you'd think it is because it should print a debug print if it found an XML that is wrong or doesn't exist instead it prints when it found an XML.. :D 
Basically all it says is that the XML exists and is not a mod :D 

If your newly added transmission doesn't work the error must be somewhere else ;)

In todays Update there were quite a few vehicles added to the basegameConfigs by Johny6210, so maybe the vehicles you need are already in there now?

**Comment by modelleicher** [comment]
I forgot to be more specific, if it says "is not a mod" it does not mean that the XML-Name exists in RMT, it should say that for every basegame vehicle that is loaded on your savegame with RMT script included.

If you have a config in basegameConfigs with the correct XML name it will then add the following print below it
name_of_xml has realManualTransmission config loaded!

**Comment by rubberburner89** [comment]
Thank you for the prompt response.  I had been spinning my wheels trying to figure out what I was doing wrong that was causing the game to crash, and after you replied, I started to look elsewhere and realized it was a corrupt save game. (Still trying to figure out what caused that). Anyways, turns out I had done everything correctly. 

And yes one of the transmissions I was looking for Johny had added. The other wasn't there nor did I expect it to be (Wanted a powershift transmission from the last generation of Puma's). 

Anyways, keep up the great work, and I look forward to future updates,
RB

P.S. You can of course consider this matter closed.
