### ISSUE TITLE
Saitek panel, joystick not shifting gears up or down

### ISSUE THREAD

**Issue by Sozzy76** [modelleicher/FS19_realManualTransmission#55]
Hi 
I had my Saitek side panel  joystick mapped to operate range and gears, however the joystick has stopped changing gears since the last update, gears now can only be done by button not axis. I also tried mapping my Logitech joystick but same it doesn't shift the gears.

can you please help?

**Comment by modelleicher** [comment]
Hi,
I never tried or thought about shifting gears with an axis. Not sure though what I changed that could cause this, I don't remember doing anything drastically different to the inputs. Also in 19 all inputs are the same no matter if axis, button, key.. 
So I need to do some investigating for that one.. 
Do the gears simply not work at all or does shifting into gear work but it doesn't stay in gear?

**Comment by Sozzy76** [comment]
I can us the joy stick for forward and backwards, but when mapped for gears moving the joystick left or right it wont change the gears, this is tested on base game vehicles so its wasn't a modded vehicle that I put a gearbox in

**Comment by miracleman51** [comment]
Im also having an issue where I cant shift into gears using any mapped gear up/down button.

Also, Im testing the Realistic Vehicle Mod that changes tire traction/physics, but you need to have selectable diff locks or 4wd to get the benefit.  I tried with EV however the diffs don't seem to lock correctly.

otherwise it (was) working great!

**Comment by modelleicher** [comment]
@miracleman51 
Any Button? Not Axis? Are you sure you could shift into gear (e.g. clutch pressed or powershift, vehicle is turned on)

As far as the diffs on EV, thats the best you're going to get. There is no way to physically lock the diff in FS (e.g. make both wheels absolutely spin together and together only) the way FS physics work you can just increase/decrease the bias for the diff.. So with the diffs locked there's still ability to spin one wheel more than the other.. 
This has been like that since FS exists and I don't think its ever going to change.
I've thought about creating some forces that like "steer" the vehicle so it can't turn with diffs active or stuff, but thats just adding complexity to a defunct system and doesn't really help anything I suppose. FS engine just isn't made for diff locks.

But you still get more traction and more "both wheel turn bias" with locked diffs than with open diff so.. its still better/more real than no difflocks imho.. (as then the bias is always towards locked by default) 
Or in other words, without EV default FS you have almost locked diffs, with EV you have slighty more locked diffs but really open diffs if you don't have diff lock on.

**Comment by miracleman51** [comment]
Yea i've tried mapping it to different buttons and doesn't work.  it was working and then it just stopped.. it won't get into gear from neutral and the text in the hud is 'bold'.

Ive tried deleting the input binding settings and deleting the mod and re loading etc.  if I tick 'swap range1 with gears' (cant remember the exact text) I get gears but no ranges.

With regards to the diffs, I understand however  all I can say is I have tested using this mod. and also mogli's VCA, and VCA seems to lock the diffs better than RMT.

**Comment by modelleicher** [comment]
@miracleman51 Maybe VCA does some physics trickery to make the diffs seem more real than EV does.. not sure I'd have to take a look at that.
But I didn't plan on adding diffs and 4wd to RMT since most people use EV anyways 

If the hud text is being bold that is just because some other mod does render bold text on screen it turns everything bold.. that shouldn't have anything to do with RMT though, but it DOES sound like a mod conflict, did you add anything to the savegame since it was working?

**Comment by miracleman51** [comment]
hmm, yes I was thinking it was a conflict, with VCA or EV, but Ive tried deleting them and re-trying... i'll have another look but it seems to me that perhaps something has messed with the gear up/down bindings or something.

**Comment by Sozzy76** [comment]
Hi, has there been any update for a fix on this or is it a mod conflict?

**Comment by Sozzy76** [comment]
sorry hit the wrong button, didn't mean to close

**Comment by Sozzy76** [comment]
I have tried setting the gears to the Saitek joystick with version 6.0.3 and it still doesn't work

**Comment by Sozzy76** [comment]
I have tried the updated version and the side panel joystick now changes gears with no issues

Thank you for fixing this
