### ISSUE TITLE
Best shifter layout

### ISSUE THREAD

**Issue by YaMoef** [modelleicher/FS19_realManualTransmission#67]
Hello,
Thanks for making this mod. I haven't used it yet but I would like to try it out. Since I'm making multiple shifters I want to ask what is the best layout to use? What I mean by this is that I should make. As example: 3 shifters with each 6 speeds, or 2 shifters with each 7 speeds. Since I gues this mods is about that. When you go into a gear you have some sort of 'subgear'.
Thank you for responding and making this mod possible!

**Comment by modelleicher** [comment]
Hello,
Most tractors IRL have up to 6 gears, and usually up to 4 ranges/groups shiftet by two shifters. Sometimes there's a Reverse gear on the main shifter, sometimes its on the group shifter. Later when power shift became more wide spread many tractors only had one shifter and 2 buttons on that shifter for powershifting.
I don't think there are many tractors with 3 shift levers IRL, usually they have two. Sometimes they have a powershift-lever instead of buttons, or a reverser-lever next to the steering wheel.

If that is what you were asking?

**Comment by YaMoef** [comment]
Thanks this was exactly what I needed.
